'use client';
import {useMemo,useState} from 'react';
import * as XLSX from 'xlsx';
import {Upload,Download,GitCompare,AlertTriangle} from 'lucide-react';
import {MASTER,AEROS,parseWorkbook,aeroTotals,grand,Snapshot} from '../engine';
const fmt=(n:number)=>n.toLocaleString('en-IN');
async function readFile(f:File):Promise<Snapshot>{const wb=XLSX.read(await f.arrayBuffer(),{type:'array'});const parsed=wb.SheetNames.map((sheetName)=>{const ws=wb.Sheets[sheetName];const rows=XLSX.utils.sheet_to_json(ws,{header:1,defval:null}) as any[][];return {sheetName,parsed:parseWorkbook(rows)}});const detailed=parsed.filter(x=>x.parsed.sourceType==='detailed').sort((a,b)=>Object.keys(b.parsed.rows||{}).length-Object.keys(a.parsed.rows||{}).length)[0];const aggregate=parsed.filter(x=>x.parsed.sourceType==='aggregate').sort((a,b)=>Number(Boolean(b.parsed.aggregate))-Number(Boolean(a.parsed.aggregate)))[0];const p=detailed?.parsed??aggregate?.parsed??{sourceType:'aggregate' as const,rows:{},aggregate:null};return {id:crypto.randomUUID(),name:f.name,uploadedAt:new Date().toISOString(),sourceType:p.sourceType,rows:p.rows,aggregate:p.aggregate}}
async function makePdf(title:string,head:string[],body:any[][]){const {jsPDF}=await import('jspdf');await import('jspdf-autotable');const doc:any=new jsPDF({orientation:'landscape',unit:'pt',format:'a4'});doc.setFontSize(11);doc.text('OFFICE OF THE ELECTORAL REGISTRATION OFFICER, AC-34, MATIALA',30,28);doc.setFontSize(9);doc.text(title,30,43);doc.autoTable({head:[head],body,startY:55,styles:{fontSize:6,cellPadding:3},headStyles:{fillColor:[48,52,58],textColor:255},alternateRowStyles:{fillColor:[248,249,250]}});doc.save(title.replace(/[^a-z0-9]+/gi,'_')+'.pdf')}
export default function Home(){
 const [latest,setLatest]=useState<Snapshot|null>(null),[comparison,setComparison]=useState<Snapshot|null>(null),[tab,setTab]=useState('overview'),[latestLoading,setLatestLoading]=useState(false),[comparisonLoading,setComparisonLoading]=useState(false);
 const uploadLatest=async(f:File)=>{setLatestLoading(true);try{setLatest(await readFile(f))}finally{setLatestLoading(false)}};
 const uploadComparison=async(f:File)=>{setComparisonLoading(true);try{setComparison(await readFile(f))}finally{setComparisonLoading(false)}};
 const aero=useMemo(()=>latest?aeroTotals(latest):[],[latest]),g=latest?grand(latest):null;
 const psRows=useMemo(()=>latest?MASTER.map((r,i)=>{const m=latest.rows[r.ps];return [i+1,r.ps,r.bloName,r.bloMobile,r.supervisor,m?.noticeGenerated??0,m?.noticeDelivered??0,m?m.deliveredPct.toFixed(2)+'%':'',m?.hearingLapse??0,m?.hearingHeld??0,m?.heldLapsed??0,m?m.heldLapsedPct.toFixed(2)+'%':'',m?.parked??0]}):[],[latest]);
 const compareRows=useMemo(()=>latest&&comparison&&latest.sourceType==='detailed'&&comparison.sourceType==='detailed'?MASTER.map(r=>{const a=comparison.rows[r.ps]||{},b=latest.rows[r.ps]||{};return [r.ps,r.bloName,r.aero,(b.noticeGenerated||0)-(a.noticeGenerated||0),(b.noticeDelivered||0)-(a.noticeDelivered||0),(b.heldLapsed||0)-(a.heldLapsed||0),(b.parked||0)-(a.parked||0)]}):[],[latest,comparison]);
 const aeroCompareRows=useMemo(()=>latest&&comparison&&latest.sourceType==='detailed'&&comparison.sourceType==='detailed'?AEROS.map(a=>{const lm=aeroTotals(latest).find(x=>x.name===a.name)||{},cm=aeroTotals(comparison).find(x=>x.name===a.name)||{};return [a.name,cm.noticeGenerated,lm.noticeGenerated,lm.noticeGenerated-cm.noticeGenerated,cm.noticeDelivered,lm.noticeDelivered,lm.noticeDelivered-cm.noticeDelivered,cm.heldLapsed,lm.heldLapsed,lm.heldLapsed-cm.heldLapsed,cm.parked,lm.parked,lm.parked-cm.parked]}):[],[latest,comparison]);
 const aggregateCompare=latest&&comparison&&latest.aggregate&&comparison.aggregate?[
  ['Notice Generated',comparison.aggregate.noticeGenerated,latest.aggregate.noticeGenerated,latest.aggregate.noticeGenerated-comparison.aggregate.noticeGenerated],
  ['Notice Delivered',comparison.aggregate.noticeDelivered,latest.aggregate.noticeDelivered,latest.aggregate.noticeDelivered-comparison.aggregate.noticeDelivered],
  ['Delivered %',comparison.aggregate.deliveredPct,latest.aggregate.deliveredPct,latest.aggregate.deliveredPct-comparison.aggregate.deliveredPct],
  ['Hearing Held + Lapsed',comparison.aggregate.heldLapsed,latest.aggregate.heldLapsed,latest.aggregate.heldLapsed-comparison.aggregate.heldLapsed],
  ['Parked',comparison.aggregate.parked,latest.aggregate.parked,latest.aggregate.parked-comparison.aggregate.parked]
 ]:null;
 const psPdf=()=>makePdf('SIR-2026 — PS-WISE NOTICE & HEARING STATUS REPORT',['S.No','P.S.','BLO Name','BLO Mobile','BLO Supervisor','Notice Generated','Notice Delivered','Delivered %','Hearing Held + Lapsed','% Held + Lapsed','Parked'],psRows);
 const aeroPdf=()=>makePdf('SIR-2026 — AERO/Ad.AERO-WISE SUMMARY — NOTICE & HEARING STATUS',['S.No','AERO / Ad.AERO','Mobile','Supervisors','Notice Generated','Notice Delivered','% Delivered','Hearing Held + Lapsed','% Held + Lapsed','Parked'],aero.map((r:any,i:number)=>[i+1,r.name,r.mobile,r.supervisorCount,r.noticeGenerated,r.noticeDelivered,r.deliveredPct.toFixed(2)+'%',r.heldLapsed,r.heldLapsedPct.toFixed(2)+'%',r.parked]));
 return <div><header className="top"><div><div className="brand">AC-34 MATIALA — NOTICE & HEARING REPORT</div><div className="sub">SIR-2026 • 430 PS • 14 AERO/Ad.AERO</div></div></header><main className="wrap">
 <div className="uploadGrid">
  <div className="uploadCard latest"><div className="uploadTitle">LATEST ECI REPORT</div><div className="uploadName">{latest?latest.name:'Upload the latest ECI Excel'}</div><label className="btn primary upload"><Upload size={16}/>{latestLoading?'Processing...':'Upload Latest ECI Excel'}<input type="file" accept=".xlsx,.xls" onChange={e=>e.target.files?.[0]&&uploadLatest(e.target.files[0])}/></label>{latest&&<div className="small">{new Date(latest.uploadedAt).toLocaleString('en-IN')} • {latest.sourceType==='detailed'?'PS-level':'AC-level'} source</div>}</div>
  <div className="uploadCard comparison"><div className="uploadTitle">COMPARISON ECI REPORT</div><div className="uploadName">{comparison?comparison.name:'Upload the older / comparison ECI Excel'}</div><label className="btn upload"><GitCompare size={16}/>{comparisonLoading?'Processing...':'Upload Comparison ECI Excel'}<input type="file" accept=".xlsx,.xls" onChange={e=>e.target.files?.[0]&&uploadComparison(e.target.files[0])}/></label>{comparison&&<div className="small">{new Date(comparison.uploadedAt).toLocaleString('en-IN')} • {comparison.sourceType==='detailed'?'PS-level':'AC-level'} source</div>}</div>
 </div>
 <div className="toolbar"><button className="btn" onClick={()=>setTab('overview')}>Overview</button><button className="btn" onClick={()=>setTab('ps')}>PS Report</button><button className="btn" onClick={()=>setTab('aero')}>AERO Summary</button><button className="btn" onClick={()=>setTab('compare')}><GitCompare size={15}/> Compare Reports</button></div>
 {!latest&&<div className="card"><h2>Start by uploading the latest ECI report</h2><p className="small">The comparison upload is separate. Upload the older ECI report in the second box above whenever you want to compare it with the latest report.</p></div>}
 {latest&&<><div className="card"><div className="small">LATEST REPORT</div><h2 style={{margin:'5px 0'}}>{latest.name}</h2><div className="small">{new Date(latest.uploadedAt).toLocaleString('en-IN')} • {latest.sourceType==='detailed'?'PS-level source':'aggregate-only source'}</div></div>
 {latest.sourceType==='aggregate'&&<div className="notice"><AlertTriangle size={15}/> The latest ECI workbook contains AC-level totals only. PS/AERO rows cannot be distributed unless the source contains PS/Part-level data.</div>}
 {g&&<div className="grid">{[['Notice Generated',g.noticeGenerated],['Notice Delivered',g.noticeDelivered],['Delivered %',g.deliveredPct],['Hearing Lapse',g.hearingLapse],['Hearing Held',g.hearingHeld],['Held + Lapsed',g.heldLapsed]].map((x:any)=><div className="metric" key={x[0]}><div className="l">{x[0]}</div><div className="v">{String(x[0]).includes('%')?x[1].toFixed(2)+'%':fmt(x[1])}</div></div>)}</div>}
 {tab==='overview'&&<div className="card"><h3>Reports generated from Latest ECI Report</h3><div className="toolbar"><button className="btn primary" disabled={latest.sourceType!=='detailed'} onClick={psPdf}><Download size={15}/> Download PS Report PDF</button><button className="btn primary" disabled={latest.sourceType!=='detailed'} onClick={aeroPdf}><Download size={15}/> Download AERO PDF</button></div></div>}
 {tab==='ps'&&<div className="card"><div className="toolbar"><h3 style={{marginRight:'auto'}}>PS-Wise / AERO-Wise Grouped Report — Latest</h3><button className="btn" disabled={latest.sourceType!=='detailed'} onClick={psPdf}>PDF</button></div><div className="tableWrap"><table className="report"><thead><tr>{['S.No','P.S. No.','BLO Name','BLO Mobile No.','BLO Supervisor','Notice Generated','Notice Delivered','% Delivered','Hearing Lapse','Hearing Held','Held + Lapsed','% Held + Lapsed','Parked'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{latest.sourceType==='detailed'&&psRows.map((r:any,i:number)=><tr key={i}>{r.map((v:any,j:number)=><td key={j} className={j>=5?'num':''}>{typeof v==='number'?fmt(v):v}</td>)}</tr>)}</tbody></table></div></div>}
 {tab==='aero'&&<div className="card"><div className="toolbar"><h3 style={{marginRight:'auto'}}>AERO / Ad.AERO Summary — Latest</h3><button className="btn" disabled={latest.sourceType!=='detailed'} onClick={aeroPdf}>PDF</button></div><div className="tableWrap"><table className="report"><thead><tr>{['S.No','AERO / Ad.AERO','Mobile','No. of Supervisors','Notice Generated','Notice Delivered','% Delivered','Hearing Lapse','Hearing Held','Held + Lapsed','% Held + Lapsed','Parked'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{latest.sourceType==='detailed'&&aero.map((r:any,i:number)=><tr key={r.name}><td>{i+1}</td><td>{r.name}</td><td>{r.mobile}</td><td className="num">{r.supervisorCount}</td><td className="num">{fmt(r.noticeGenerated)}</td><td className="num">{fmt(r.noticeDelivered)}</td><td className="num">{r.deliveredPct.toFixed(2)}%</td><td className="num">{fmt(r.hearingLapse)}</td><td className="num">{fmt(r.hearingHeld)}</td><td className="num">{fmt(r.heldLapsed)}</td><td className="num">{r.heldLapsedPct.toFixed(2)}%</td><td className="num">{fmt(r.parked)}</td></tr>)}</tbody></table></div></div>}
 {tab==='compare'&&<div className="card"><h3>Comparison — Latest vs Comparison ECI Report</h3>{!comparison?<div className="notice">Upload the comparison ECI report in the second upload box above.</div>:latest.sourceType==='detailed'&&comparison.sourceType==='detailed'?<div>
 <h4>PS-wise Comparison — Comparison vs Latest</h4>
 <div className="tableWrap"><table className="report"><thead><tr>{['P.S.','BLO','AERO','Notice Gen — Comparison','Notice Gen — Latest','Notice Gen Δ','Notice Delivered — Comparison','Notice Delivered — Latest','Notice Delivered Δ','Held + Lapsed — Comparison','Held + Lapsed — Latest','Held + Lapsed Δ','Parked — Comparison','Parked — Latest','Parked Δ'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{compareRows.map((r:any)=>{const ps=r[0],a=comparison.rows[ps]||{},b=latest.rows[ps]||{};const vals=[ps,r[1],r[2],a.noticeGenerated||0,b.noticeGenerated||0,r[3],a.noticeDelivered||0,b.noticeDelivered||0,r[4],a.heldLapsed||0,b.heldLapsed||0,r[5],a.parked||0,b.parked||0,r[6]];return <tr key={ps}>{vals.map((v:any,j:number)=><td key={j} className={[5,8,11,14].includes(j)?'delta '+(v>0?'pos':v<0?'neg':'zero'):j>=3?'num':''}>{typeof v==='number'?( [5,8,11,14].includes(j)?(v>0?'+':'')+fmt(v):fmt(v)):v}</td>)}</tr>})}</tbody></table></div>
 <h4 style={{marginTop:24}}>AERO-wise Comparison — Comparison vs Latest</h4>
 <div className="tableWrap"><table className="report"><thead><tr>{['AERO / Ad.AERO','Notice Gen — Comparison','Notice Gen — Latest','Notice Gen Δ','Notice Delivered — Comparison','Notice Delivered — Latest','Notice Delivered Δ','Held + Lapsed — Comparison','Held + Lapsed — Latest','Held + Lapsed Δ','Parked — Comparison','Parked — Latest','Parked Δ'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{aeroCompareRows.map((r:any)=><tr key={r[0]}>{r.map((v:any,j:number)=><td key={j} className={[3,6,9,12].includes(j)?'delta '+(v>0?'pos':v<0?'neg':'zero'):j>0?'num':''}>{typeof v==='number'?([3,6,9,12].includes(j)?(v>0?'+':'')+fmt(v):fmt(v)):v}</td>)}</tr>)}</tbody></table></div>
 </div>:aggregateCompare?<div className="tableWrap"><table className="report"><thead><tr><th>Metric</th><th>Comparison Report</th><th>Latest Report</th><th>Change</th></tr></thead><tbody>{aggregateCompare.map((r:any)=><tr key={r[0]}><td>{r[0]}</td><td className="num">{r[0]==='Delivered %'?r[1].toFixed(2)+'%':fmt(r[1])}</td><td className="num">{r[0]==='Delivered %'?r[2].toFixed(2)+'%':fmt(r[2])}</td><td className={'num delta '+(r[3]>0?'pos':r[3]<0?'neg':'zero')}>{r[3]>0?'+':''}{r[0]==='Delivered %'?r[3].toFixed(2)+' pp':fmt(r[3])}</td></tr>)}</tbody></table></div>:<div className="notice">Both files need compatible PS-level or AC-level data for comparison.</div>}</div>}
 </>}
 <div className="footer">Master mapping: 430 PS from the supplied PS-wise AERO-wise reference report. Latest and comparison uploads are kept separately in this page session.</div></main></div>
}