'use client';
import {useEffect,useMemo,useState} from 'react';
import * as XLSX from 'xlsx';
import {Upload,Download,GitCompare,History,AlertTriangle} from 'lucide-react';
import {MASTER,AEROS,parseWorkbook,aeroTotals,grand,Snapshot} from '../engine';
const STORE='ac34_notice_history_v2'; const fmt=(n:number)=>n.toLocaleString('en-IN');
async function makePdf(title:string,head:string[],body:any[][]){const {jsPDF}=await import('jspdf');await import('jspdf-autotable');const doc:any=new jsPDF({orientation:'landscape',unit:'pt',format:'a4'});doc.setFontSize(11);doc.text('OFFICE OF THE ELECTORAL REGISTRATION OFFICER, AC-34, MATIALA',30,28);doc.setFontSize(9);doc.text(title,30,43);doc.autoTable({head:[head],body,startY:55,styles:{fontSize:6,cellPadding:3},headStyles:{fillColor:[48,52,58],textColor:255}});doc.save(title.replace(/[^a-z0-9]+/gi,'_')+'.pdf')}
export default function Home(){
 const [current,setCurrent]=useState<Snapshot|null>(null),[history,setHistory]=useState<Snapshot[]>([]),[tab,setTab]=useState('overview'),[prevId,setPrevId]=useState('');
 useEffect(()=>{try{setHistory(JSON.parse(localStorage.getItem(STORE)||'[]'))}catch{}},[]);
 function save(s:Snapshot){const h=[s,...history.filter(x=>x.id!==s.id)].slice(0,40);setHistory(h);localStorage.setItem(STORE,JSON.stringify(h));setCurrent(s)}
 async function upload(f:File){const wb=XLSX.read(await f.arrayBuffer(),{type:'array'});const ws=wb.Sheets[wb.SheetNames[0]];const rows=XLSX.utils.sheet_to_json(ws,{header:1,defval:null}) as any[][];const p=parseWorkbook(rows);save({id:crypto.randomUUID(),name:f.name,uploadedAt:new Date().toISOString(),sourceType:p.sourceType,rows:p.rows,aggregate:p.aggregate})}
 const aero=useMemo(()=>current?aeroTotals(current):[],[current]),g=current?grand(current):null,prev=history.find(x=>x.id===prevId);
 const psRows=useMemo(()=>current?MASTER.map((r,i)=>{const m=current.rows[r.ps];return [i+1,r.ps,r.bloName,r.bloMobile,r.supervisor,m?.noticeGenerated??0,m?.noticeDelivered??0,m?m.deliveredPct.toFixed(2)+'%':'',m?.hearingLapse??0,m?.hearingHeld??0,m?.heldLapsed??0,m?m.heldLapsedPct.toFixed(2)+'%':'',m?.parked??0]}):[],[current]);
 const compare=useMemo(()=>prev&&current&&prev.sourceType==='detailed'&&current.sourceType==='detailed'?MASTER.map(r=>{const a=prev.rows[r.ps]||{},b=current.rows[r.ps]||{};return [r.ps,r.bloName,r.aero,(b.noticeGenerated||0)-(a.noticeGenerated||0),(b.noticeDelivered||0)-(a.noticeDelivered||0),(b.hearingHeld||0)-(a.hearingHeld||0),(b.hearingLapse||0)-(a.hearingLapse||0),(b.parked||0)-(a.parked||0)]}):[],[prev,current]);
 const psPdf=()=>makePdf('SIR-2026 — PS-WISE NOTICE & HEARING STATUS REPORT',['S.No','P.S.','BLO Name','BLO Mobile','BLO Supervisor','Notice Generated','Notice Delivered','Delivered %','Hearing Lapse','Hearing Held','Held + Lapsed','% Held + Lapsed','Parked'],psRows);
 const aeroPdf=()=>makePdf('SIR-2026 — AERO/Ad.AERO-WISE SUMMARY — NOTICE & HEARING STATUS',['S.No','AERO / Ad.AERO','Mobile','Supervisors','Notice Generated','Notice Delivered','% Delivered','Hearing Lapse','Hearing Held','Held + Lapsed','% Held + Lapsed','Parked'],aero.map((r:any,i:number)=>[i+1,r.name,r.mobile,r.supervisorCount,r.noticeGenerated,r.noticeDelivered,r.deliveredPct.toFixed(2)+'%',r.hearingLapse,r.hearingHeld,r.heldLapsed,r.heldLapsedPct.toFixed(2)+'%',r.parked]));
 const nav=(x:string)=>setTab(x);
 return <div><header className="top"><div><div className="brand">AC-34 MATIALA — NOTICE & HEARING REPORT</div><div className="sub">SIR-2026 • 430 PS • 14 AERO/Ad.AERO</div></div></header><main className="wrap">
 <div className="toolbar"><label className="btn primary upload"><Upload size={16}/> Upload ECI Excel<input type="file" accept=".xlsx,.xls" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/></label><button className="btn" onClick={()=>nav('ps')}>PS Report</button><button className="btn" onClick={()=>nav('aero')}>AERO Summary</button><button className="btn" onClick={()=>nav('compare')}><GitCompare size={15}/> Compare</button><button className="btn" onClick={()=>nav('history')}><History size={15}/> History</button></div>
 {!current&&<div className="card"><h2>Upload the latest ECI Excel</h2><p className="small">The master PS → BLO Supervisor → AERO mapping from your supplied 28.09.2026 reference report is embedded.</p><div className="notice"><AlertTriangle size={15}/> The supplied ECI workbook is aggregate-only. It has AC-level totals but no PS/Part Number rows, so the app will not invent a PS/AERO distribution. A PS-level ECI export is required for automatic 430-PS regeneration.</div></div>}
 {current&&<><div className="card"><div className="small">CURRENT SNAPSHOT</div><h2 style={{margin:'5px 0'}}>{current.name}</h2><div className="small">{new Date(current.uploadedAt).toLocaleString('en-IN')} • {current.sourceType==='detailed'?'PS-level source':'aggregate-only source'}</div></div>
 {current.sourceType==='aggregate'&&<div className="notice">This upload updates only AC-level totals. PS/AERO tables and PS comparisons are disabled because the source contains no PS-level distribution.</div>}
 {g&&<div className="grid">{[['Notice Generated',g.noticeGenerated],['Notice Delivered',g.noticeDelivered],['Delivered %',g.deliveredPct],['Hearing Lapse',g.hearingLapse],['Hearing Held',g.hearingHeld],['Held + Lapsed',g.heldLapsed]].map((x:any)=><div className="metric" key={x[0]}><div className="l">{x[0]}</div><div className="v">{String(x[0]).includes('%')?x[1].toFixed(2)+'%':fmt(x[1])}</div></div>)}</div>}
 <div className="tabs">{['overview','ps','aero','compare','history'].map(x=><button className={'tab '+(tab===x?'active':'')} onClick={()=>nav(x)} key={x}>{x==='ps'?'PS Report':x==='aero'?'AERO Summary':x[0].toUpperCase()+x.slice(1)}</button>)}</div>
 {tab==='overview'&&<div className="card"><h3>Reports</h3><div className="toolbar"><button className="btn primary" disabled={current.sourceType!=='detailed'} onClick={psPdf}><Download size={15}/> Download PS Report PDF</button><button className="btn primary" disabled={current.sourceType!=='detailed'} onClick={aeroPdf}><Download size={15}/> Download AERO PDF</button></div><p className="small">Upload every 2 hours. Each upload is saved as a snapshot in this browser for later comparison.</p></div>}
 {tab==='ps'&&<div className="card"><div className="toolbar"><h3 style={{marginRight:'auto'}}>PS-Wise / AERO-Wise Grouped Report</h3><button className="btn" disabled={current.sourceType!=='detailed'} onClick={psPdf}>PDF</button></div><div className="tableWrap"><table className="report"><thead><tr>{['S.No','P.S. No.','BLO Name','BLO Mobile No.','BLO Supervisor','Notice Generated','Notice Delivered','% Delivered','Hearing Lapse','Hearing Held','Held + Lapsed','% Held + Lapsed','Parked'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{current.sourceType==='detailed'&&psRows.map((r:any,i:number)=><tr key={i}>{r.map((v:any,j:number)=><td key={j} className={j>=5?'num':''}>{typeof v==='number'?fmt(v):v}</td>)}</tr>)}</tbody></table></div></div>}
 {tab==='aero'&&<div className="card"><div className="toolbar"><h3 style={{marginRight:'auto'}}>AERO / Ad.AERO Summary</h3><button className="btn" disabled={current.sourceType!=='detailed'} onClick={aeroPdf}>PDF</button></div><div className="tableWrap"><table className="report"><thead><tr>{['S.No','AERO / Ad.AERO','Mobile','No. of Supervisors','Notice Generated','Notice Delivered','% Delivered','Hearing Lapse','Hearing Held','Held + Lapsed','% Held + Lapsed','Parked'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{current.sourceType==='detailed'&&aero.map((r:any,i:number)=><tr key={r.name}><td>{i+1}</td><td>{r.name}</td><td>{r.mobile}</td><td className="num">{r.supervisorCount}</td><td className="num">{fmt(r.noticeGenerated)}</td><td className="num">{fmt(r.noticeDelivered)}</td><td className="num">{r.deliveredPct.toFixed(2)}%</td><td className="num">{fmt(r.hearingLapse)}</td><td className="num">{fmt(r.hearingHeld)}</td><td className="num">{fmt(r.heldLapsed)}</td><td className="num">{r.heldLapsedPct.toFixed(2)}%</td><td className="num">{fmt(r.parked)}</td></tr>)}</tbody></table></div></div>}
 {tab==='compare'&&<div className="card"><h3>Compare Two Snapshots</h3><select className="btn" value={prevId} onChange={e=>setPrevId(e.target.value)}><option value="">Select previous snapshot</option>{history.filter(x=>x.id!==current.id).map(x=><option value={x.id} key={x.id}>{new Date(x.uploadedAt).toLocaleString('en-IN')} — {x.name}</option>)}</select>{prev&&current&&current.sourceType==='detailed'&&prev.sourceType==='detailed'?<div className="tableWrap" style={{marginTop:14}}><table className="report"><thead><tr>{['P.S.','BLO','AERO','Notice Gen Δ','Notice Delivered Δ','Hearing Held Δ','Hearing Lapse Δ','Parked Δ'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{compare.map((r:any)=><tr key={r[0]}>{r.map((v:any,j:number)=><td key={j} className={j>=3?'delta '+(v>0?'pos':v<0?'neg':'zero'):''}>{j>=3?(v>0?'+':'')+fmt(v):v}</td>)}</tr>)}</tbody></table></div>:<div className="notice" style={{marginTop:14}}>Comparison needs two PS-level snapshots.</div>}</div>}
 {tab==='history'&&<div className="card"><h3>Snapshot History</h3>{history.map(x=><div className="chip" key={x.id} style={{marginBottom:7}}><b>{new Date(x.uploadedAt).toLocaleString('en-IN')}</b> — {x.name}<div className="small">{x.sourceType}</div></div>)}</div>}
 </>}
 <div className="footer">Master mapping: 430 PS from the supplied PS-wise AERO-wise reference report.</div></main></div>
}